### ISSUE TITLE
Version 1.0 Checklist

### ISSUE THREAD

**Issue by jaswilli** [globus/globus-cli#70]
### Checklist for the 1.0 release
- [x] Control python warnings with an env var (#17)
- [x] Add --map-http-status global option to convert HTTP statuses into nonzero exit codes  (#21)
- [x] `globus transfer async-transfer` and `globus-transfer async-delete` should print out the Task ID in text mode (#29)
- [ ] Produce more useful error on endpoints where autoactivation fails to activate (#30)
- [ ] Enumerate and address all cases of commands where `--format TEXT` is the JSON output (#35)
- [x] Add `globus logout` command (#38)
- [x] ~~Decide on whether or not to use positional arguments for commands with (at present) required options~~ (#39)
- [x] Required options should become positional arguments (#81)
- [x] Generic error handlers are exiting with status 0, not status 1 (#40)
- [x] Remove `globus transfer endpoint autoactivate` (#42)
- [x] Show latest version on output from --version (#43)
- [ ] Recursive dir listing has potentially dangerous implications service-side -- limit it or remove it (#46)
- [x] Allow the Transfer service to figure out what the default path should be when `ls`ing (#49)
- [x] globus login, add output describing result/action after entering Authorization code (#52)
- [x] Transfer: support "-a" option on endpoint ls (#55)
- [x] Transfer: review output from task show (#56)
- [ ] Transfer: add options to task list (#57)
- [ ] Transfer: add options to task event-list (#58)
- [ ] Transfer: task wait behavior (#59)
- [x] Transfer: add "--all" option to task cancel (#60)
- [ ] Transfer: implement replacement for "details -t" (#62)
- [ ] Transfer: endpoint create/update functionality (#63)
- [x] Transfer: does endpoint-type=s3 work for endpoint create? (#64)
- [ ] Verify that we're handling encoding (utf8) correctly (#65)
- [x] Transfer: add "size" sync-level option (#66)
- [x] Transfer: async-transfer default sync-level (#67)
- [x] Transfer: missing `async-transfer` options (#68)
- [x] Transfer: missing `async-delete` options (#69)
- [x] **Command heirarchy/grouping** (#71)
- [x] Add EndpointPlusPath Parameter Type (#73)
- [x] Add a `bookmark show` option suitable for use in a subshell (#74)
- [ ] Login: add support for "local http server" mode (#75)
- [x] Store and use access tokens in the configuration file (#83)
- [x] Command line paths with batch mode (#89)
- [ ] Clean up help strings (consistent line endings (periods), etc.)
- [x] Add `whoami` command (#44)

**Comment by sirosen** [comment]
Trying to prioritize this list, I decided sort things out into "speculative" and "non-speculative" for now.
I don't mean to distinguish things which are important, but ones where there is a clear path forward from ones that are underspecified or otherwise hazy.
For my own purposes, this will make them easier to consume -- others are welcome to criticize / help me reprioritize.

These lists are sorted by priority, as I see them.

Non-Speculative:
- Add globus logout command (#38)
- globus login, add output describing result/action after entering Authorization code (#52)
- Transfer: add options to task list (#57)
- Transfer: add options to task event-list (#58)
- Transfer: implement replacement for "details -t" (#62)
- Transfer: endpoint create/update functionality (#63)
- Enumerate and address all cases of commands where --format TEXT is the JSON output (#35)
- Login: add support for "local http server" mode (#75)

Speculative:
- Produce more useful error on endpoints where autoactivation fails to activate (#30)
- Recursive dir listing has potentially dangerous implications service-side -- limit it or remove it (#46)
- Transfer: review output from task show (#56)
- Transfer: task wait behavior (#59)
- Verify that we're handling encoding (utf8) correctly (#65)
- Clean up help strings (consistent line endings (periods), etc.)

**Comment by sirosen** [comment]
I'm closing this as it's redundant with the 1.0 milestone and hasn't been kept up to date.
